In [1]:
import numpy as np

In [2]:
class LogisticRegression:
    def __init__(self,learning_rate=0.01,epochs=5000):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.weights = None
        self.bais = None
    def sigmoid(self,z):
        return 1/(1+np.exp(-z))
    def fit(self,x,y):
        self.n_features = x.shape[1]
        n_instances = x.shape[0]
        self.weights = np.zeros(self.n_features)
        self.bais = 0
        lr = self.learning_rate
        for _ in range(self.epochs):
            
            y_output = np.dot(x,self.weights) + self.bais
            d_loss = (1/n_instances)*(np.dot(x.T,self.sigmoid(y_output)-y))
            d_bais = (1/n_instances)*(np.sum(self.sigmoid(y_output)-y))
            predictions = np.clip(self.sigmoid(y_output),1e-15,1-1e-15)
            loss = -np.mean(y*np.log(predictions)+(1-y)*np.log(1-predictions))
            if _ %100 == 0 :
                print(loss)
            self.weights -= d_loss*lr
            self.bais -= d_bais*lr
            if _ == 0 :            
                print("predictions",predictions)
                print("weights",self.weights)
                print("bais",self.bais)
                new_output = np.dot(x, self.weights) + self.bais
                print("Min z:", np.min(new_output))
                print("Max z:", np.max(new_output))
    def predict_proba(self,x):
        y_out = np.dot(x,self.weights)+self.bais
        return self.sigmoid(y_out)
    def predict(self,x):
       return np.where(self.predict_proba(x) >= 0.5,1,0)

In [3]:
import pandas as pd
data = pd.read_csv(r"C:\Users\bhava\Downloads\studyvspassdata\marks.csv")
data.head()

    e1_score   e2_score  result
0  34.623660  78.024693       0
1  30.286711  43.894998       0
2  35.847409  72.902198       0
3  60.182599  86.308552       1
4  79.032736  75.344376       1

In [4]:
data = data.reset_index()
data.head()

   index   e1_score   e2_score  result
0      0  34.623660  78.024693       0
1      1  30.286711  43.894998       0
2      2  35.847409  72.902198       0
3      3  60.182599  86.308552       1
4      4  79.032736  75.344376       1

In [5]:
from zlib import crc32
def test_set_check(identifier,test_ratio):
    return crc32(np.int64(identifier))& 0xFFFFFFFF< test_ratio*2**32

In [6]:
def split_data_id(test_ratio,id_column):
    id = data[id_column]
    in_test_set = id.apply(lambda id_:test_set_check(id_,test_ratio))
    return data.loc[~in_test_set],data.loc[in_test_set]

In [7]:
train,test = split_data_id(0.1,"index")

In [8]:
train_y = train["result"]
train_x = train.drop("result",axis=1)
train_x = train_x.drop("index",axis=1)
test_y = test["result"]
test_x = test.drop("result",axis=1)
test_x = test_x.drop("index",axis=1)

In [9]:
train_x.head()

    e1_score   e2_score
0  34.623660  78.024693
1  30.286711  43.894998
2  35.847409  72.902198
3  60.182599  86.308552
4  79.032736  75.344376

In [10]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
pipe = Pipeline([
    ("imputer",SimpleImputer(strategy = "median")) ,
("std_scaler",StandardScaler())])

In [11]:
train_x = pd.DataFrame(
    pipe.fit_transform(train_x),
    columns=train_x.columns,
    
)

test_x = pd.DataFrame(
    pipe.transform(test_x),
    columns=test_x.columns,
   
)

In [12]:
print(train_x)

     e1_score  e2_score
0   -1.119646  0.696856
1   -1.302164 -0.748323
2   -1.068144  0.479950
3   -0.044007  1.047625
4    0.749295  0.583361
..        ...       ...
125  0.291467 -2.219387
126 -0.886882 -1.923353
127 -2.486120  0.278894
128 -1.131162  0.121502
129 -1.514343 -2.558729

[130 rows x 2 columns]

In [13]:

model = LogisticRegression()
model.fit(train_x,train_y)

0.6931471805599453
predictions [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
 0.5 0.5 0.5 0.5]
weights [0.00322074 0.00287079]
bais 0.00038461538461538467
Min z: -0.011838253632770282
Max z: 0.008396304389069069
0.5510905992343635
0.4682819087043826
0.4153079697954933
0.37857164477490857
0.3514940852542627
0.3306056430017211
0.31392425687436565
0.3002397094101139
0.28877164962143975
0.27899382677190765
0.27053788055598266
0.2631377772602969
0.25659621746912736
0.250763512805359
0.2455238434718466
0.24078604814026405
0.23647728819907965
0.23253858754499898
0.2289216275649299
0.22558640137782549
0.22249946838753978
0.21963263601224697
0.21696195049612602
0.21446691477408095
0.21212987545748901
0.20993553740001217
0.20787057563630498
0.20592332244283632
0.20408351293413052
0.2023420766925641
0.20069096591143926
0.19912301273190744
0.19763181009595676
0.19621161167423506
0.1948572473674763
0.19356405160104384
0.19232780218920134
0.19114466797963464
0.19001116382913777
0.18892411173021545
0.18788060712205237
0.18687798959019375
0.18591381729673645
0.18498584459399503
0.184092002364972
0.1832303807077912
0.18239921364184716
0.18159686556338617
0.18082181921960386

In [14]:
test_x = test_x.drop("index",axis=1,errors="ignore")
y_test_pred = model.predict(test_x)

In [15]:
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score,recall_score
precision_score(y_test_pred,test_y)

1.0

In [16]:
f1_score(y_test_pred,test_y)

0.9411764705882353

In [17]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test_pred,test_y)

0.9230769230769231

In [18]:
from sklearn.linear_model import LogisticRegression
m1 = LogisticRegression(max_iter=1000)
m1.fit(train_x,train_y)
res = m1.predict(test_x)
accuracy_score(res,test_y)

0.9230769230769231

In [19]:
print(type(train_x))
print(train_x.shape)

print(type(train_y))
print(train_y.shape)

<class 'pandas.core.frame.DataFrame'>
(130, 2)
<class 'pandas.core.series.Series'>
(130,)

In [20]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(test_y, y_test_pred))
print(m1.coef_)
print(m1.intercept_)
print(model.weights)
print(model.bais)

[[4 1]
 [0 8]]
[[2.60351409 2.55959043]]
[0.07520501]
[2.65309984 2.58298041]
0.07532233268007203